import fs from 'fs'
import path from 'path'

// 1. PRISMA SCHEMA GUNCELLEMESI (Favoriler tablosu eklendi)
const prismaSchema = [
  'generator client {',
  '  provider = "prisma-client-js"',
  '}',
  'datasource db {',
  '  provider = "postgresql"',
  '  url      = env("DATABASE_URL")',
  '}',
  'model User {',
  '  id            String         @id @default(uuid())',
  '  name          String?',
  '  email         String         @unique',
  '  password      String',
  '  role          Role           @default(USER)',
  '  createdAt     DateTime       @default(now())',
  '  tickets       Ticket[]',
  '  savedProjects SavedProject[]',
  '}',
  'model Project {',
  '  id         String         @id @default(uuid())',
  '  title      String',
  '  videoUrl   String',
  '  categories String',
  '  tags       String?',
  '  status     String         @default("Active")',
  '  createdAt  DateTime       @default(now())',
  '  savedBy    SavedProject[]',
  '}',
  'model SavedProject {',
  '  id        String   @id @default(uuid())',
  '  userId    String',
  '  projectId String',
  '  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)',
  '  project   Project  @relation(fields: [projectId], references: [id], onDelete: Cascade)',
  '  createdAt DateTime @default(now())',
  '  @@unique([userId, projectId])',
  '}',
  'model FAQ {',
  '  id       String @id @default(uuid())',
  '  question String',
  '  answer   String',
  '}',
  'model Ticket {',
  '  id        String   @id @default(uuid())',
  '  subject   String',
  '  message   String',
  '  status    String   @default("OPEN")',
  '  userId    String',
  '  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)',
  '  createdAt DateTime @default(now())',
  '}',
  'enum Role {',
  '  USER',
  '  ADMIN',
  '}'
].join('\n')

fs.writeFileSync(path.join(process.cwd(), 'prisma/schema.prisma'), prismaSchema, 'utf8')

// 2. DASHBOARD VERILERINI GETIREN API
const dashboardApi = [
  "import { PrismaClient } from '@prisma/client'",
  'const prisma = new PrismaClient()',
  'export default defineEventHandler(async (event) => {',
  "  const userId = getCookie(event, 'auth_token')",
  "  if(!userId) throw createError({ statusCode: 401, statusMessage: 'Unauthorized' })",
  '  const savedProjects = await prisma.savedProject.findMany({',
  '    where: { userId },',
  '    include: { project: true },',
  "    orderBy: { createdAt: 'desc' }",
  '  })',
  '  const tickets = await prisma.ticket.findMany({',
  '    where: { userId },',
  "    orderBy: { createdAt: 'desc' }",
  '  })',
  '  return {',
  '    savedProjects: savedProjects.map(sp => sp.project),',
  '    tickets',
  '  }',
  '})'
].join('\n')

// 3. PROJE KAYDETME (SAVE) API'Sİ
const saveProjectApi = [
  "import { PrismaClient } from '@prisma/client'",
  'const prisma = new PrismaClient()',
  'export default defineEventHandler(async (event) => {',
  "  const userId = getCookie(event, 'auth_token')",
  "  if(!userId) throw createError({ statusCode: 401, statusMessage: 'Unauthorized' })",
  '  const body = await readBody(event)',
  '  const { projectId } = body',
  '  if(!projectId) throw createError({ statusCode: 400 })',
  '  const existing = await prisma.savedProject.findUnique({',
  '    where: { userId_projectId: { userId, projectId } }',
  '  })',
  '  if(existing) {',
  '    await prisma.savedProject.delete({ where: { id: existing.id } })',
  "    return { saved: false, message: 'Removed' }",
  '  } else {',
  '    await prisma.savedProject.create({ data: { userId, projectId } })',
  "    return { saved: true, message: 'Saved' }",
  '  }',
  '})'
].join('\n')

// 4. TICKET (DESTEK) GONDERME API'Sİ
const createTicketApi = [
  "import { PrismaClient } from '@prisma/client'",
  'const prisma = new PrismaClient()',
  'export default defineEventHandler(async (event) => {',
  "  const userId = getCookie(event, 'auth_token')",
  "  if(!userId) throw createError({ statusCode: 401, statusMessage: 'Unauthorized' })",
  '  const body = await readBody(event)',
  '  const { subject, message } = body',
  '  const ticket = await prisma.ticket.create({',
  '    data: { subject, message, userId }',
  '  })',
  '  return ticket',
  '})'
].join('\n')

const apiDirUser = path.join(process.cwd(), 'server/api/user')
const apiDirProjects = path.join(process.cwd(), 'server/api/projects')
const apiDirTickets = path.join(process.cwd(), 'server/api/tickets')

if (!fs.existsSync(apiDirUser)) fs.mkdirSync(apiDirUser, { recursive: true })
if (!fs.existsSync(apiDirProjects)) fs.mkdirSync(apiDirProjects, { recursive: true })
if (!fs.existsSync(apiDirTickets)) fs.mkdirSync(apiDirTickets, { recursive: true })

fs.writeFileSync(path.join(apiDirUser, 'dashboard.get.ts'), dashboardApi, 'utf8')
fs.writeFileSync(path.join(apiDirProjects, 'save.post.ts'), saveProjectApi, 'utf8')
fs.writeFileSync(path.join(apiDirTickets, 'index.post.ts'), createTicketApi, 'utf8')

// 5. GUNCEL DASHBOARD SAYFASI (app/pages/dashboard.vue)
const dashboardPage = [
  '<script setup lang="ts">',
  "useSeoMeta({ title: 'My Dashboard' })",
  "const { data: user, pending: userPending } = await useFetch('/api/auth/me')",
  "if (!userPending.value && !user.value) { if (typeof window !== 'undefined') window.location.href = '/sign-in' }",
  "const { data: dashboardData, pending: dashPending } = await useFetch('/api/user/dashboard')",
  'const handleLogout = async () => {',
  "  await $fetch('/api/auth/logout', { method: 'POST' })",
  "  window.location.href = '/'",
  '}',
  'const formatDate = (dateString: string) => {',
  "  return new Date(dateString).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })",
  '}',
  '</script>',
  '<template>',
  '  <div v-if="user" class="min-h-screen bg-[#fafafa] pt-24 pb-12 px-6">',
  '    <div class="max-w-[1200px] mx-auto">',
  '      <div class="flex justify-between items-end mb-10 border-b border-zinc-200 pb-6">',
  '        <div>',
  '          <h1 class="text-3xl font-bold text-black tracking-tight">Dashboard</h1>',
  '          <p class="text-zinc-500 mt-1">Welcome back, {{ user.name }}. Manage your saved items and tickets here.</p>',
  '          <div v-if="user.role === \'ADMIN\'" class="mt-4">',
  '            <NuxtLink to="/admin" class="bg-indigo-50 text-indigo-700 px-4 py-2 rounded-lg text-xs font-bold uppercase tracking-wide border border-indigo-100 hover:bg-indigo-100 transition-colors">',
  '              Go to Admin Panel ->',
  '            </NuxtLink>',
  '          </div>',
  '        </div>',
  '        <button @click="handleLogout" class="px-5 py-2.5 bg-zinc-200 hover:bg-zinc-300 rounded-xl text-sm font-medium transition-colors text-black">',
  '          Log Out',
  '        </button>',
  '      </div>',
  '      <div v-if="dashPending" class="animate-pulse text-zinc-400">Loading your dashboard data...</div>',
  '      <div v-else class="grid grid-cols-1 lg:grid-cols-3 gap-10">',
  '        ',
  '        <div class="lg:col-span-2">',
  '          <h2 class="text-xl font-semibold mb-6 text-black">Saved Inspirations ({{ dashboardData?.savedProjects?.length || 0 }})</h2>',
  '          <div v-if="dashboardData?.savedProjects?.length === 0" class="p-8 bg-white rounded-2xl border border-zinc-200 text-zinc-500 text-center">',
  "            You haven't saved any projects yet. Browse the homepage and bookmark your favorites!",
  '          </div>',
  '          <div v-else class="grid grid-cols-1 sm:grid-cols-2 gap-6">',
  '            <div v-for="proj in dashboardData.savedProjects" :key="proj.id" class="bg-white p-4 rounded-2xl border border-zinc-200 shadow-sm flex flex-col gap-4 group cursor-pointer">',
  '              <div class="w-full aspect-video rounded-xl bg-zinc-100 overflow-hidden relative">',
  '                <video :src="proj.videoUrl" autoplay loop muted playsinline class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"></video>',
  '              </div>',
  '              <div>',
  '                <h3 class="font-medium text-black">{{ proj.title }}</h3>',
  '                <p class="text-sm text-zinc-500">{{ proj.categories }}</p>',
  '              </div>',
  '            </div>',
  '          </div>',
  '        </div>',
  '        ',
  '        <div>',
  '          <div class="flex justify-between items-center mb-6">',
  '            <h2 class="text-xl font-semibold text-black">My Tickets</h2>',
  '            <NuxtLink to="/ticket" class="text-sm text-blue-600 hover:underline">New Ticket</NuxtLink>',
  '          </div>',
  '          <div v-if="dashboardData?.tickets?.length === 0" class="p-6 bg-white rounded-2xl border border-zinc-200 text-zinc-500 text-center text-sm">',
  '            No support tickets found.',
  '          </div>',
  '          <div v-else class="bg-white border border-zinc-200 rounded-2xl overflow-hidden shadow-sm">',
  '            <div v-for="ticket in dashboardData.tickets" :key="ticket.id" class="p-5 border-b border-zinc-100 last:border-0 hover:bg-zinc-50 transition-colors cursor-pointer">',
  '              <div class="flex justify-between items-start mb-2">',
  '                <span class="text-xs font-mono text-zinc-400">ID: {{ ticket.id.substring(0,8) }}</span>',
  "                <span :class=\"ticket.status === 'OPEN' ? 'bg-amber-100 text-amber-700' : 'bg-zinc-100 text-zinc-500'\" class=\"px-2 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase\">",
  '                  {{ ticket.status }}',
  '                </span>',
  '              </div>',
  '              <h3 class="font-medium text-black text-sm mb-1">{{ ticket.subject }}</h3>',
  '              <p class="text-xs text-zinc-500">{{ formatDate(ticket.createdAt) }}</p>',
  '            </div>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  </div>',
  '</template>'
].join('\n')
fs.writeFileSync(path.join(process.cwd(), 'app/pages/dashboard.vue'), dashboardPage, 'utf8')

// 6. GUNCEL TICKET SAYFASI (app/pages/ticket.vue)
const ticketPage = [
  '<script setup lang="ts">',
  "import { ref } from 'vue'",
  "useSeoMeta({ title: 'Support & FAQ' })",
  "const { data: user } = await useFetch('/api/auth/me')",
  'const faqs = [',
  "  { q: 'What is Inspo Clone?', a: 'It is a curated library of website inspirations and components.' },",
  "  { q: 'How can I submit a component?', a: 'You can submit your own component via the Submit link in the footer.' },",
  "  { q: 'How do I save projects?', a: 'Just click the Save button on any project modal. You need to be logged in.' }",
  ']',
  'const activeFaq = ref<number | null>(0)',
  'const toggleFaq = (index: number) => activeFaq.value = activeFaq.value === index ? null : index',
  "const form = ref({ subject: '', message: '' })",
  'const isSubmitting = ref(false)',
  "const successMsg = ref('')",
  'const submitTicket = async () => {',
  "  if (!user.value) { alert('You need to sign in to submit a ticket.'); window.location.href = '/sign-in'; return; }",
  '  isSubmitting.value = true;',
  '  try {',
  "    await $fetch('/api/tickets', { method: 'POST', body: form.value })",
  "    successMsg.value = 'Ticket submitted successfully! We will get back to you soon.'",
  "    form.value = { subject: '', message: '' }",
  "  } catch (error) { alert('Failed to submit ticket.') }",
  '  finally { isSubmitting.value = false }',
  '}',
  '</script>',
  '<template>',
  '  <div class="max-w-[1200px] mx-auto py-24 px-6">',
  '    <div class="text-center mb-16">',
  '      <h1 class="text-4xl md:text-5xl font-bold mb-4 tracking-tight">Help & Support</h1>',
  '      <p class="text-zinc-500 text-lg">Find answers to common questions or reach out to us directly.</p>',
  '    </div>',
  '    <div class="flex flex-col lg:flex-row gap-12 lg:gap-24">',
  '      <div class="w-full lg:w-1/2">',
  '        <h2 class="text-2xl font-semibold mb-6">Frequently Asked Questions</h2>',
  '        <div class="flex flex-col gap-4">',
  '          <div v-for="(faq, i) in faqs" :key="i" class="border border-zinc-200 rounded-2xl overflow-hidden bg-zinc-50/50">',
  '            <button @click="toggleFaq(i)" class="w-full px-6 py-5 flex justify-between items-center text-left font-medium text-black hover:bg-zinc-100 transition-colors">',
  '              {{ faq.q }}',
  '            </button>',
  '            <div v-show="activeFaq === i" class="px-6 pb-5 text-zinc-600 leading-relaxed text-sm">{{ faq.a }}</div>',
  '          </div>',
  '        </div>',
  '      </div>',
  '      <div class="w-full lg:w-1/2">',
  '        <h2 class="text-2xl font-semibold mb-6">Submit a Ticket</h2>',
  '        <form @submit.prevent="submitTicket" class="bg-white p-8 rounded-[2rem] border border-zinc-200 flex flex-col gap-5 shadow-xl shadow-zinc-200/50">',
  '          <div v-if="successMsg" class="bg-emerald-50 text-emerald-600 p-4 rounded-xl text-sm border border-emerald-100">{{ successMsg }}</div>',
  '          <div>',
  '            <label class="block text-sm font-medium text-zinc-700 mb-2">Subject</label>',
  '            <input v-model="form.subject" type="text" required placeholder="e.g. Account Issue" class="w-full bg-zinc-50 border border-zinc-200 rounded-xl px-5 py-4 text-black focus:outline-none focus:ring-2 focus:ring-black focus:border-transparent transition-all" />',
  '          </div>',
  '          <div>',
  '            <label class="block text-sm font-medium text-zinc-700 mb-2">Message</label>',
  '            <textarea v-model="form.message" required rows="5" placeholder="How can we help you?" class="w-full bg-zinc-50 border border-zinc-200 rounded-xl px-5 py-4 text-black focus:outline-none focus:ring-2 focus:ring-black focus:border-transparent transition-all resize-none"></textarea>',
  '          </div>',
  '          <button type="submit" :disabled="isSubmitting" class="w-full bg-black text-white py-4 mt-2 rounded-xl font-medium hover:bg-zinc-800 transition-colors disabled:opacity-70">',
  "            {{ isSubmitting ? 'Sending...' : 'Send Message' }}",
  '          </button>',
  '        </form>',
  '      </div>',
  '    </div>',
  '  </div>',
  '</template>'
].join('\n')
fs.writeFileSync(path.join(process.cwd(), 'app/pages/ticket.vue'), ticketPage, 'utf8')

// 7. PRODUCT MODAL (SAVE BUTONU AKTİF)
const modalContent = [
  '<script setup lang="ts">',
  "import { ref, watch, onUnmounted } from 'vue'",
  'const props = defineProps<{ isOpen: boolean, item: any }>()',
  "const emit = defineEmits(['close'])",
  "const close = () => emit('close')",
  "const { data: user } = await useFetch('/api/auth/me')",
  'const isSaving = ref(false)',
  'const saveProject = async () => {',
  "  if (!user.value) { alert('Kaydetmek icin lutfen giris yapin!'); window.location.href = '/sign-in'; return; }",
  '  isSaving.value = true;',
  '  try {',
  "    const res = await $fetch('/api/projects/save', { method: 'POST', body: { projectId: props.item.id } })",
  "    alert(res.saved ? 'Video Dashboard paneline kaydedildi!' : 'Video favorilerden cikarildi.')",
  "  } catch(e) { alert('Bir hata olustu.') }",
  '  finally { isSaving.value = false }',
  '}',
  "watch(() => props.isOpen, (val) => { if (typeof document !== 'undefined') document.body.style.overflow = val ? 'hidden' : '' })",
  "onUnmounted(() => { if (typeof document !== 'undefined') document.body.style.overflow = '' })",
  '</script>',
  '<template>',
  '  <Teleport to="body">',
  '    <Transition enter-active-class="transition duration-300 ease-out" enter-from-class="opacity-0" enter-to-class="opacity-100" leave-active-class="transition duration-200 ease-in" leave-from-class="opacity-100" leave-to-class="opacity-0">',
  '      <div v-if="isOpen" class="fixed inset-0 z-[100] flex items-center justify-center p-4">',
  '        <div class="absolute inset-0 bg-zinc-900/80 backdrop-blur-sm" @click="close"></div>',
  '        <Transition enter-active-class="transition duration-400 ease-out delay-75" enter-from-class="opacity-0 translate-y-8 scale-95" enter-to-class="opacity-100 translate-y-0 scale-100" leave-active-class="transition duration-200 ease-in" leave-from-class="opacity-100 translate-y-0 scale-100" leave-to-class="opacity-0 translate-y-8 scale-95">',
  '          <div v-if="isOpen" class="relative w-full max-w-6xl bg-white rounded-[2rem] shadow-2xl overflow-hidden flex flex-col md:flex-row h-[85vh]">',
  '            <button @click="close" class="absolute top-6 right-6 z-20 p-3 bg-black/5 hover:bg-black/10 text-black rounded-full transition-colors backdrop-blur-md">',
  '               <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>',
  '            </button>',
  '            <div class="w-full md:w-2/3 bg-[#f4f4f5] p-6 md:p-12 flex items-center justify-center">',
  '               <div class="w-full relative rounded-2xl overflow-hidden shadow-lg border border-black/5 bg-black">',
  '                 <video autoplay loop muted playsinline class="w-full aspect-video object-cover">',
  '                    <source :src="item?.video" type="video/mp4" />',
  '                 </video>',
  '               </div>',
  '            </div>',
  '            <div class="w-full md:w-1/3 p-8 md:p-12 flex flex-col bg-white">',
  '               <div class="flex gap-2 mb-6">',
  '                 <span v-for="tag in item?.tags" :key="tag" class="bg-zinc-100 text-zinc-600 px-3 py-1 rounded-full text-[11px] font-mono tracking-widest uppercase">{{ tag }}</span>',
  '               </div>',
  '               <h2 class="text-4xl font-medium tracking-tight text-black mb-1">{{ item?.title }}</h2>',
  '               <p class="text-[15px] text-zinc-500 font-light mb-8">{{ item?.categories?.join(\', \') }}</p>',
  '               <p class="text-zinc-600 leading-relaxed mb-8 text-sm">Detailed inspection of the component. Ready for your next big project.</p>',
  '               <div class="mt-auto flex flex-col gap-4">',
  '                 <button class="w-full bg-black text-white py-4 rounded-xl font-medium hover:bg-zinc-800 transition-colors shadow-lg shadow-black/10">Purchase Source Code</button>',
  '                 <div class="flex gap-4">',
  '                   <button class="flex-1 bg-zinc-100 text-black py-4 rounded-xl font-medium hover:bg-zinc-200 transition-colors">Live Demo</button>',
  '                   <button @click="saveProject" :disabled="isSaving" class="flex-1 border border-zinc-200 text-black py-4 rounded-xl font-medium hover:bg-zinc-50 transition-colors disabled:opacity-50">',
  "                     {{ isSaving ? 'Saving...' : 'Save to Dashboard' }}",
  '                   </button>',
  '                 </div>',
  '               </div>',
  '            </div>',
  '          </div>',
  '        </Transition>',
  '      </div>',
  '    </Transition>',
  '  </Teleport>',
  '</template>'
].join('\n')
fs.writeFileSync(path.join(process.cwd(), 'app/components/Product/Modal.vue'), modalContent, 'utf8')

console.log('✅ Dashboard, Ticket ve Favori kaydetme (Save) sistemleri kuruldu!')
